from sqlalchemy import Column, Integer, String, Date, Text
from app.database import Base

class Employee(Base):
    __tablename__ = "employees"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    designation = Column(String, index=True)
    department = Column(String, index=True)
    joining_date = Column(Date)
    manager = Column(String)
    contact = Column(String)
    skills = Column(String) # Comma-separated or JSON string
    bio = Column(Text, nullable=True) # Generated by AI
    document_path = Column(String, nullable=True) # Path to uploaded doc
